### ISSUE TITLE
Docker image pubblished

### ISSUE THREAD

**Issue by Allan-Nava** [getevo/evo#8]
Next step is to create a docker image with EVO Framework pre installed.

https://docs.github.com/en/actions/guides/publishing-docker-images

```

The build-push-action options required for GitHub Packages are:

username: You can use the ${{ github.actor }} context to automatically use the username of the user that triggered the workflow run. For more information, see "Context and expression syntax for GitHub Actions."
password: You can use the automatically-generated GITHUB_TOKEN secret for the password. For more information, see "Authenticating with the GITHUB_TOKEN."
registry: Must be set to docker.pkg.github.com.
repository: Must be set in the format OWNER/REPOSITORY/IMAGE_NAME. For example, for an image named octo-image stored on GitHub at http://github.com/octo-org/octo-repo, the repository option should be set to octo-org/octo-repo/octo-image.
name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: my-org/my-repo/my-image
          tag_with_ref: true
```
